### ISSUE TITLE
Alpha in video_animation_rayshade should be a parameter

### ISSUE THREAD

**Issue by jose1711** [zappingseb/rayshaderanimate#9]
Not sure why but with the default settings I am barely seeing the overlay map when using `video_animation_rayshade` function. If I increase the `alphalayer` variable the result is much better:

![obrázok](https://user-images.githubusercontent.com/1406222/113709351-af22c980-96e2-11eb-91c6-1ed9612b2ac0.png)

Therefore I think alpha should be exported as a parameter of `video_animation_rayshade`.

**Comment by zappingseb** [comment]
Hi @jose1711 , I am currently not really working on this package anymore... Do you want to create a pull request with all your desired changes? I will just merge it in...

**Comment by jose1711** [comment]
I might try that (only installed R after finding your package - otherwise I have zero previous knowledge)

**Comment by zappingseb** [comment]
Ah, ok. Sorry, currently I am founding a start-up called [Keepoala](https://www.keepoala.com), that's why I have zero time for the project, sadly.
